#!/usr/bin/env python
import os
import json
import subprocess
import time

def load_config():
    homedir = os.path.expanduser('~')
    conffile = os.path.join(homedir,'.metade.conf')
    with open(conffile) as config_file:
        config = json.load(config_file)
    return config

def exec_startup():
    for item, binary in configuration.iteritems():
        if binary is not None:
            print 'running', binary
            subprocess.Popen(binary)
            #subprocess.call(binary)
            print 'running', binary

configuration = load_config()
exec_startup()

while True:
    time.sleep(30)
